// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: client_interface.proto
#ifndef GRPC_client_5finterface_2eproto__INCLUDED
#define GRPC_client_5finterface_2eproto__INCLUDED

#include "client_interface.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace greyvarproto {

class ClientInterface final {
 public:
  static constexpr char const* service_full_name() {
    return "greyvarproto.ClientInterface";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status OnEntityMoved(::grpc::ClientContext* context, const ::greyvarproto::EntityMoved& request, ::greyvarproto::NoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::greyvarproto::NoResponse>> AsyncOnEntityMoved(::grpc::ClientContext* context, const ::greyvarproto::EntityMoved& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::greyvarproto::NoResponse>>(AsyncOnEntityMovedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::greyvarproto::NoResponse>> PrepareAsyncOnEntityMoved(::grpc::ClientContext* context, const ::greyvarproto::EntityMoved& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::greyvarproto::NoResponse>>(PrepareAsyncOnEntityMovedRaw(context, request, cq));
    }
    virtual ::grpc::Status OnPlayerQuit(::grpc::ClientContext* context, const ::greyvarproto::PlayerQuit& request, ::greyvarproto::NoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::greyvarproto::NoResponse>> AsyncOnPlayerQuit(::grpc::ClientContext* context, const ::greyvarproto::PlayerQuit& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::greyvarproto::NoResponse>>(AsyncOnPlayerQuitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::greyvarproto::NoResponse>> PrepareAsyncOnPlayerQuit(::grpc::ClientContext* context, const ::greyvarproto::PlayerQuit& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::greyvarproto::NoResponse>>(PrepareAsyncOnPlayerQuitRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void OnEntityMoved(::grpc::ClientContext* context, const ::greyvarproto::EntityMoved* request, ::greyvarproto::NoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void OnPlayerQuit(::grpc::ClientContext* context, const ::greyvarproto::PlayerQuit* request, ::greyvarproto::NoResponse* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::greyvarproto::NoResponse>* AsyncOnEntityMovedRaw(::grpc::ClientContext* context, const ::greyvarproto::EntityMoved& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::greyvarproto::NoResponse>* PrepareAsyncOnEntityMovedRaw(::grpc::ClientContext* context, const ::greyvarproto::EntityMoved& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::greyvarproto::NoResponse>* AsyncOnPlayerQuitRaw(::grpc::ClientContext* context, const ::greyvarproto::PlayerQuit& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::greyvarproto::NoResponse>* PrepareAsyncOnPlayerQuitRaw(::grpc::ClientContext* context, const ::greyvarproto::PlayerQuit& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status OnEntityMoved(::grpc::ClientContext* context, const ::greyvarproto::EntityMoved& request, ::greyvarproto::NoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::greyvarproto::NoResponse>> AsyncOnEntityMoved(::grpc::ClientContext* context, const ::greyvarproto::EntityMoved& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::greyvarproto::NoResponse>>(AsyncOnEntityMovedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::greyvarproto::NoResponse>> PrepareAsyncOnEntityMoved(::grpc::ClientContext* context, const ::greyvarproto::EntityMoved& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::greyvarproto::NoResponse>>(PrepareAsyncOnEntityMovedRaw(context, request, cq));
    }
    ::grpc::Status OnPlayerQuit(::grpc::ClientContext* context, const ::greyvarproto::PlayerQuit& request, ::greyvarproto::NoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::greyvarproto::NoResponse>> AsyncOnPlayerQuit(::grpc::ClientContext* context, const ::greyvarproto::PlayerQuit& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::greyvarproto::NoResponse>>(AsyncOnPlayerQuitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::greyvarproto::NoResponse>> PrepareAsyncOnPlayerQuit(::grpc::ClientContext* context, const ::greyvarproto::PlayerQuit& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::greyvarproto::NoResponse>>(PrepareAsyncOnPlayerQuitRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void OnEntityMoved(::grpc::ClientContext* context, const ::greyvarproto::EntityMoved* request, ::greyvarproto::NoResponse* response, std::function<void(::grpc::Status)>) override;
      void OnPlayerQuit(::grpc::ClientContext* context, const ::greyvarproto::PlayerQuit* request, ::greyvarproto::NoResponse* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::greyvarproto::NoResponse>* AsyncOnEntityMovedRaw(::grpc::ClientContext* context, const ::greyvarproto::EntityMoved& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::greyvarproto::NoResponse>* PrepareAsyncOnEntityMovedRaw(::grpc::ClientContext* context, const ::greyvarproto::EntityMoved& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::greyvarproto::NoResponse>* AsyncOnPlayerQuitRaw(::grpc::ClientContext* context, const ::greyvarproto::PlayerQuit& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::greyvarproto::NoResponse>* PrepareAsyncOnPlayerQuitRaw(::grpc::ClientContext* context, const ::greyvarproto::PlayerQuit& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_OnEntityMoved_;
    const ::grpc::internal::RpcMethod rpcmethod_OnPlayerQuit_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status OnEntityMoved(::grpc::ServerContext* context, const ::greyvarproto::EntityMoved* request, ::greyvarproto::NoResponse* response);
    virtual ::grpc::Status OnPlayerQuit(::grpc::ServerContext* context, const ::greyvarproto::PlayerQuit* request, ::greyvarproto::NoResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_OnEntityMoved : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_OnEntityMoved() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_OnEntityMoved() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnEntityMoved(::grpc::ServerContext* context, const ::greyvarproto::EntityMoved* request, ::greyvarproto::NoResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnEntityMoved(::grpc::ServerContext* context, ::greyvarproto::EntityMoved* request, ::grpc::ServerAsyncResponseWriter< ::greyvarproto::NoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_OnPlayerQuit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_OnPlayerQuit() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_OnPlayerQuit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnPlayerQuit(::grpc::ServerContext* context, const ::greyvarproto::PlayerQuit* request, ::greyvarproto::NoResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnPlayerQuit(::grpc::ServerContext* context, ::greyvarproto::PlayerQuit* request, ::grpc::ServerAsyncResponseWriter< ::greyvarproto::NoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_OnEntityMoved<WithAsyncMethod_OnPlayerQuit<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_OnEntityMoved : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_OnEntityMoved() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithCallbackMethod_OnEntityMoved<BaseClass>, ::greyvarproto::EntityMoved, ::greyvarproto::NoResponse>(
          [this](::grpc::ServerContext* context,
                 const ::greyvarproto::EntityMoved* request,
                 ::greyvarproto::NoResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->OnEntityMoved(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithCallbackMethod_OnEntityMoved() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnEntityMoved(::grpc::ServerContext* context, const ::greyvarproto::EntityMoved* request, ::greyvarproto::NoResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void OnEntityMoved(::grpc::ServerContext* context, const ::greyvarproto::EntityMoved* request, ::greyvarproto::NoResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_OnPlayerQuit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_OnPlayerQuit() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithCallbackMethod_OnPlayerQuit<BaseClass>, ::greyvarproto::PlayerQuit, ::greyvarproto::NoResponse>(
          [this](::grpc::ServerContext* context,
                 const ::greyvarproto::PlayerQuit* request,
                 ::greyvarproto::NoResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->OnPlayerQuit(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithCallbackMethod_OnPlayerQuit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnPlayerQuit(::grpc::ServerContext* context, const ::greyvarproto::PlayerQuit* request, ::greyvarproto::NoResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void OnPlayerQuit(::grpc::ServerContext* context, const ::greyvarproto::PlayerQuit* request, ::greyvarproto::NoResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_OnEntityMoved<ExperimentalWithCallbackMethod_OnPlayerQuit<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_OnEntityMoved : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_OnEntityMoved() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_OnEntityMoved() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnEntityMoved(::grpc::ServerContext* context, const ::greyvarproto::EntityMoved* request, ::greyvarproto::NoResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_OnPlayerQuit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_OnPlayerQuit() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_OnPlayerQuit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnPlayerQuit(::grpc::ServerContext* context, const ::greyvarproto::PlayerQuit* request, ::greyvarproto::NoResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnEntityMoved : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_OnEntityMoved() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_OnEntityMoved() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnEntityMoved(::grpc::ServerContext* context, const ::greyvarproto::EntityMoved* request, ::greyvarproto::NoResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnEntityMoved(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnPlayerQuit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_OnPlayerQuit() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_OnPlayerQuit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnPlayerQuit(::grpc::ServerContext* context, const ::greyvarproto::PlayerQuit* request, ::greyvarproto::NoResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnPlayerQuit(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_OnEntityMoved : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_OnEntityMoved() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithRawCallbackMethod_OnEntityMoved<BaseClass>, ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->OnEntityMoved(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithRawCallbackMethod_OnEntityMoved() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnEntityMoved(::grpc::ServerContext* context, const ::greyvarproto::EntityMoved* request, ::greyvarproto::NoResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void OnEntityMoved(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_OnPlayerQuit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_OnPlayerQuit() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithRawCallbackMethod_OnPlayerQuit<BaseClass>, ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->OnPlayerQuit(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithRawCallbackMethod_OnPlayerQuit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnPlayerQuit(::grpc::ServerContext* context, const ::greyvarproto::PlayerQuit* request, ::greyvarproto::NoResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void OnPlayerQuit(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OnEntityMoved : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_OnEntityMoved() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::greyvarproto::EntityMoved, ::greyvarproto::NoResponse>(std::bind(&WithStreamedUnaryMethod_OnEntityMoved<BaseClass>::StreamedOnEntityMoved, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_OnEntityMoved() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnEntityMoved(::grpc::ServerContext* context, const ::greyvarproto::EntityMoved* request, ::greyvarproto::NoResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOnEntityMoved(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::greyvarproto::EntityMoved,::greyvarproto::NoResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OnPlayerQuit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_OnPlayerQuit() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::greyvarproto::PlayerQuit, ::greyvarproto::NoResponse>(std::bind(&WithStreamedUnaryMethod_OnPlayerQuit<BaseClass>::StreamedOnPlayerQuit, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_OnPlayerQuit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnPlayerQuit(::grpc::ServerContext* context, const ::greyvarproto::PlayerQuit* request, ::greyvarproto::NoResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOnPlayerQuit(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::greyvarproto::PlayerQuit,::greyvarproto::NoResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_OnEntityMoved<WithStreamedUnaryMethod_OnPlayerQuit<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_OnEntityMoved<WithStreamedUnaryMethod_OnPlayerQuit<Service > > StreamedService;
};

}  // namespace greyvarproto


#endif  // GRPC_client_5finterface_2eproto__INCLUDED
